add support for windows
sindresorhus/default-browser pull request #6
Opened 2020-04-09 15:09 UTC by connor4312

I had to adjust some linting rules as it looks like `xo` has changed in the years since this module was first written. I've also kept with the `>=4` version constraint, which makes code less pretty. I can update that to >=8 as part of this PR, or a separate PR--let me know if you want that 🙂

2020-04-12 15:23 UTC, sindresorhus commented
> I can update that to >=8 as part of this PR

Yeah, feel free to require Node.js 10 in this PR, and also update the dependencies.

2020-04-12 15:26 UTC, sindresorhus commented on index.js
> +const windows = require('./windows');
You need to add this file to `files` in package.json.

2020-06-15 02:43 UTC, shazron commented
@connor4312 will you have time to update the PR? if not I can use your code and submit a new PR based on it, with the changes.

2020-09-08 16:06 UTC, connor4312 commented
I've updated the PR :)

2020-09-08 16:39 UTC, connor4312 commented
It looks like `com.apple.launchservices.secure.plist` isn't available on the OSX machines that Travis uses: https://travis-ci.com/github/sindresorhus/default-browser/jobs/382419730

2020-09-28 19:48 UTC, sindresorhus commented
> Yeah, feel free to require Node.js 10 in this PR, and also update the dependencies.

Node.js **10**

2020-09-28 19:50 UTC, sindresorhus requested changes

2020-09-28 19:50 UTC, sindresorhus commented on package.json
> +    "xdg-default-browser": "^2.1.0"
Upgrade the dependencies to latest.

2020-09-28 19:50 UTC, sindresorhus commented on windows.js
> +// Windows doesn't have browser IDs in the same way OSX/Linux does--give fake
`OSX` => `macOS`

2020-09-28 19:50 UTC, sindresorhus commented on windows.js
> +	MSEdgeDHTML: {name: 'Edge', id: 'com.microsoft.edge'}, // On OSX, its "com.microsoft.edgemac"
`it's`

2020-09-28 19:50 UTC, sindresorhus commented on windows.js
> +util.inherits(UnknownBrowserError, Error);
Use normal ES6 subclassing.

2020-09-28 19:51 UTC, sindresorhus commented
You need to mention Windows support in the readme.

2021-02-04 04:22 UTC, DannyFeliz commented
@connor4312 👀

2021-02-04 20:13 UTC, connor4312 commented
Thanks for the ping. Updated dependencies as requested. The update to tsd caused an issue in tests complaining about a lack of `esModuleInterop` for the default import, so I changed that to an `import *`.

2021-02-04 20:18 UTC, connor4312 commented
Looks like the test failure is caused by `default-browser-id`. Not sure what the deal there is -- the module works on Catalina and Big Sur, maybe Github Actions' macOS setup is set up differently than a standard osx install.

2021-02-07 08:56 UTC, sindresorhus requested changes

2021-02-07 08:56 UTC, sindresorhus commented on package.json
> +    "node": ">=8"
You can target Node.js 12 now.

2021-02-07 08:56 UTC, sindresorhus commented on windows.js
> +	const match = /ProgId\s*REG_SZ\s*(\S+)/.exec(result.stdout);
Use named capture group.

2021-02-07 08:56 UTC, sindresorhus commented on windows.js
> +	// Execa@0.10 throws if the command fails--no need to check `result.failed`
This comment mentions an old Execa version.

2021-02-07 08:56 UTC, sindresorhus commented on windows.js
> +		throw new UnknownBrowserError(`Cannot find windows browser in stdout: ${JSON.stringify(result.stdout)}`);
```suggestion
		throw new UnknownBrowserError(`Cannot find Windows browser in stdout: ${JSON.stringify(result.stdout)}`);
```

2021-03-07 13:06 UTC, merged